version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bom_manager_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: bom_user
      POSTGRES_PASSWORD: bom_password
      POSTGRES_DB: bom_manager
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
